server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}/

spring:
  application:
    name: spring-security-form-based
  security:
    user:
      name: srivatsan
      password: password
      roles: ADMIN

